name: Build and Release

on: [push, pull_request]

jobs:
  build:
     
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pip install pyinstaller
          shell: bash

        - name: Build Executable
          run: pyinstaller --add-data "images;images" --onefile ETABS_to_RAM_APP.py --name=ETABS_RAM_bridge.exe 


        - name: Upload Executable as Artifact
          uses: actions/upload-artifact@v2
          with:
                name: ETABS_RAM_bridge
                path: dist/